# Generated by Django 4.2.5 on 2023-11-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_trainer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='plan_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
    ]
