# Generated by Django 4.2.5 on 2023-11-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_enroll_due_date_enroll_payment_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
