# Generated by Django 4.2.5 on 2023-11-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_alter_enroll_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
