# Generated by Django 4.2.5 on 2024-08-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_alter_enroll_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='payment_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
